AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: CodeDeploy to test and shift traffic to a updated deployed version

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: src/
      DeploymentPreference:
        # AllAtOnce
        # Canary10Percent30Minutes
        # Canary10Percent5Minutes
        # Canary10Percent10Minutes
        # Linear10PercentEvery10Minutes
        # Linear10PercentEvery1Minute
        # Linear10PercentEvery2Minutes
        Type: #Edit This Part!!
      Events:
        Get:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId: !Ref HttpApi
      Handler: index.lambda_handler
      Runtime: python3.8

Outputs:
  ApiUrl:
    Description: HTTP API invoke URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
  LambdaFunction:
    Description: Lambda Function name
    Value: !Ref ApiFunction
